_Prtg.Lang = _Prtg.Lang || { ___: '_Prtg.Lang' };
$.extend(true, _Prtg.Lang, {
	Dialogs: {
		strings: {
			'continue': '<#langjs key="html.global.continuegt" default="Continue &gt;">',
			'deleteObject' :'<#langjs key="html.global.deleteit" default="Delete Object">',
			'cancelDeleteObject': '<#langjs key="html.global.no2" default="No, I do not want to delete this object">',
			"deleteObjects": '<#langjs key="html.global.deleteitmulti" default="Delete Objects">',
			"cancelDeleteObjects": '<#langjs key="html.global.no2multi" default="No, I do not want to delete these objects">',
			'ok': '<#langjs key="html.global.ok" default="OK">',
			'cancel': '<#langjs key="html.global.cancel" default="Cancel">',
			'checkport': '<#langjs key="html.wizarddialog.checkport" default="Checking Port">',
			'checkportok': '<#langjs key="html.wizarddialog.checkportok" default="Port OK">',
			"approvediscover": '<#langjs key="html.wizarddialog.approvediscover" default="Approve and auto-discover new probe">',
			"approve": '<#langjs key="html.wizarddialog.approve" default="Approve new probe">',
			"connectionlostdialog": '<#langjs key="js.clienttimer.lostconnectionnew2" default="<h2>Lost connection to PRTG server!</h2><p>Can not continue!</p>">',
			"connectionlosttitle": '<#langjs key="js.clienttimer.requestfailedtitle" default="Connection Problems">',
			"multieditworking": '<#langjs key="html.multiedit.working" default="Working">',
			"multieditdialogtitle": '<#langjs key="html.multiedit.dialogtitle" default="Saving...">',
			"hidethiswindow": '<#langjs key="html.global.hidethiswindow" default="Hide this window">',
			"multieditmessage2": '<#langjs key="html.multiedit.message2" default="Your changes are saved.">',
			"addmultipleuserhelp": '<#langjs key="html.adduser.addUsershelp" default="This dialog allows you to quickly add multiple new user accounts to PRTG by pasting a set of email addresses below.">',
			"addmultipleuserlable": '<#langjs key="html.adduser.addUserListgroupselect1" default="User group to add new users to:">',
			"addmultipleuserlable2": '<#langjs key="html.adduser.newuseremails" default="Email addresses:">',
			"addingusers": '<#langjs key="js.adduser.addingnewusers" default="Adding new Users.">',
			"onemoment": '<#langjs key="js.objecttools.pleasewait" default="One moment please...">',
			"loading": '<#langjs key="js.adduser.loading" default="Loading">',
			"addmultipleusertitle": '<#langjs key="html.adduser.addUserListhead" default="Add Multiple Users">',
			"addmultipleuserdonetitle": '<#langjs key="html.adduser.usersaddeddone" default="Users added">',
			"createTemplateResults": '<#langjs key="html.createtemplate.dialogtitle" default="Create Template Results">',
			"createTemplateMessage": '<#langjs key="html.createtemplate.message2" default="Congratulations! Your device template is now ready. It contains the following sensors:">',
			"takeScreenShot": '<#langjs key="html.feedback.takeScreenshot" default="Do you want to include a screenshot in your feedback?">',
			"sendFeedback": '<#langjs key="html.errorreport.submit2" default="Send Feedback">',
			"hideFeedback": '<#langjs key="html.errorreport.hidefeedback" default="Hide Feedback Button">',
      "homepageTitle": '<#langjs key="html.homepage.title" default="The current page is now your homepage!">',
			"homepageMessage": '<#langjs key="html.homepage.message" default="You will be taken to this page upon login and every time you select &quot;home&quot; from the menu.">',
			"ticketassig":'<#langjs key="js.dialogs.ticketassign" default="Assign">',
			"ticketassigning":'<#langjs key="js.dialogs.ticketassigning" default="Assigning...">',
			"ticketresolve": '<#langjs key="pas.webserverhtmlenginetables.render.maketablemenu.tickets.resolve" default="Resolve">',
			"ticketresolving":'<#langjs key="js.dialogs.ticketresolving" default="Resolving...">',
			"ticketreopen": '<#langjs key="pas.webserverhtmlenginetables.render.maketablemenu.tickets.reopen" default="Reopen">',
			"ticketclose": '<#langjs key="pas.webserverhtmlenginetables.render.maketablemenu.tickets.close" default="Close">',
			"ticketclosing": '<#langjs key="js.dialogs.ticketclosing" default="Closing...">',
      'selectdaterange': '<#langjs key="js.dialogs.selectdaterange" default="Select A Date Range">',
      'assignedtome': '<#langjs key="js.tickets.assignedtome" default="me">',
      'needserverrestarttitle': '<#langjs key="js.dialog.needserverrestarttitle" default="PRTG Core Server Restart Required">',
      'needserverrestart': '<#langjs key="js.dialog.needserverrestart" default="To apply the new settings the PRTG core server will now be restarted!">',
      'needserverrestarthint': '<#langjs key="js.dialog.needserverrestarthint" default="All users of the web interface, the Enterprise Console, or the mobile apps will be disconnected for a few minutes.">',
      'doyouwanttocontinue': '<#langjs key="js.dialog.doyouwanttocontinue" default="Do you want to continue?">',
      'serverrestarting': '<#langjs key="js.dialog.serverrestarting" default="Restarting PRTG Core Server">',
      'serverrestartinfo': '<#langjs key="html.serverrestarting.waituntilrestart" default="Restarting core service and web server now. This takes a few minutes. Afterwards you are automatically taken to the login screen. Please wait...">',
      'serverrestartpreurltext': '<#langjs key="html.serverrestarting.preurltext" default=" After the restart, your server will be reachable on:">',
      'serverrestartinfonoautoreload': '<#langjs key="html.serverrestarting.waituntilrestartnoreloadinfo" default="Restarting core service and web server now. This takes a few minutes. Please wait, then reload the link below until the server comes up again.">',
      'savewarning': '<#langjs key="html.dialog.warning.savetext" default="Do you want to save your changes? If you click &quot;Discard Changes&quot; the data you changed will be lost!">',
      "savewarningtitle": '<#langjs key="html.dialog.warning.savetitle" default="Save changes?">',
      "close": '<#langjs key="html.dialog.close" default="Close">',
      'approving': '<#langjs key="html.probe.approving" default="Approving probe">',
      'denying': '<#langjs key="html.probe.denying" default="Denying probe">',
      'addingsensors': '<#langjs key="html.recommendedsensor.addingsensors" default="Adding recommended Sensors">',
      'deleteobjecttitle': '<#langjs key="html.dialog.deleteobjecttitle" default="Delete Object?">',
      'deleteobjecttext': '<#langjs key="html.dialog.deleteobjecttext" default="Are you sure that you want to delete this object?">',

      'recommedermessagetitle': '<#langjs key="html.dialog.recommedermessagetitle" default="Recommended Sensors">',
      'recommedermessage': '<#langjs key="html.dialog.recommedermessage" default="Creating Sensors.  They will appear in the sensor list soon.">',
      'recommedenowmessage': '<#langjs key="html.dialog.recommedenowmessage" default="Running recommender service. The information is available soon.">',
      'recommederservice': '<#langjs key="html.dialog.recommederservice" default="Recommender Service">',
      'notifytesttitle': '<#langjs key="html.dialog.notifytesttitle" default="Notification Test Results">',
      'notifytestmessage': '<#langjs key="html.dialog.notifytestmessage" default="A test notification was triggered and queued for delivery to the following recipients. Please check if you received the notification.">',
      'nonotifytestmessage': '<#langjs key="html.dialog.nonotifytestmessage" default="No notification. Please check your notification&apos;s configuration.">',

      'sslTitle': '<#langjs key="html.you_should_use_ssl.wanttoswitch" default="Do you want to switch to SSL?">',
      'sslButton': '<#langjs key="html.sslnagscreen.buttontextyes" default="Yes, switch to SSL now">',
      'sslRestart': '<#langjs key="html.sslnagscreen.switchingandrestarting" default="Enabling SSL and Restart">',
      'sslMessageA': '<#langjs key="html.sslnagscreen.waituntilrestart" default="PRTG will now change settings and restart the core server service. Once finished, this website will automatically re-load the web interface via an SSL encrypted connection (<a href=https://www.paessler.com/manuals/prtg/ssl_certificate_warning.htm target=_blank>More information</a>).<p>Please wait until PRTG is restarted...">',
      'sslMessageB': '<#langjs key="html.sslnagscreen.waituntilrestart2" default="PRTG will now change settings and restart the core server service. (<a href=https://www.paessler.com/manuals/prtg/ssl_certificate_warning.htm target=_blank>More information</a>).<p>Please wait a few minutes and goto: ">',
      'sslGrowlA': '<#langjs key="html.sslnagscreen.error1" default="SSL Reminder could not be hidden">',
      'sslGrowlB': '<#langjs key="html.sslnagscreen.error2" default="SSL Reminder has been hidden">',

      'deactivatinglicensetitle': '<#langjs key="html.licesningdata.deactivatinglicensetitle" default="Deactivate License">',
      'deactivatinglicensequestion': '<#langjs key="html.licesningdata.deactivatinglicensequestion" default="If you deactivate the license on this computer, PRTG will revert to the Freeware Edition after 30 days.<br><br>Are you sure you want to deactivate this license?">',
      'deactivatinglicense': '<#langjs key="html.licesningdata.deactivatinglicense" default="Deactivating License">'
		}
	}
});
