(function($,window,document,undefined){var pluginName="prtg-table";function prtgTable(element,data,parent){this.data=data;this.el=!(element instanceof jQuery)?element:element[0];this.$el=!(element instanceof jQuery)?$(element):element;this.parent=parent;this.$parent=$(parent);this.timer=this.$parent.Events();this.$form=this.$el.find("form[refreshurl]");this.refreshurl=null;if(this.$form.length){this.refreshurl=this.$form.attr("refreshurl");this.params=_Prtg.Util.getUrlParameters(window.decodeURI(this.refreshurl));
this.refreshurl=this.refreshurl.split("?")[0];this.initEvents();this.$form.attr("callerid",this.$form.attr("id"));if(this.$el.find(".tablemultiselectcheckbox").length)this.enableSelectable();if(!this.params.tabletitle||this.params.tabletitle==="AUTO"){var currentTableTitle=this.$el.find(".tabletitle th").text();if(currentTableTitle!=="")this.params.tabletitle=this.$el.find(".tabletitle th").text()}}if(!!this.data.sortable)this.sortable=this.$el.prtgsortable(data,parent,true)[0].refresh()}prtgTable.prototype.initEvents=
function(){var self=this;if(!self.$form.data().hasOwnProperty("noAutoRefresh")){this.timer.subscribe("refresh.events.prtg",null,self,self.refresh);this.timer.subscribeOnce("navigate.prtg",null,self,function(e){self.timer.unsubscribe("refresh.events.prtg",self.refresh)})}this.$el.closest("#displaytable").off("click").on("click","tbody tr",function(event){event.stopImmediatePropagation();_Prtg.objectTools.channelEditDialog($(this).find(".editchannelsettings").data().sensorid,$(this).find(".editchannelsettings").data().channelid)});
if(this.$el.find(".tablemultiselectcheckbox").length)this.$el.on("click","tbody.ui-selectable tr",function(event){if($(event.target).is("input, .favstar, .favempty, a")||$(this).is(".notselectable")||$(event.target).is(".favstar, .favempty"))return;var $this=$(this);var $tcheckbox=$this.find(".tablemultiselectcheckbox");var checked;if($tcheckbox.length>0){checked=$tcheckbox.prop("checked");$tcheckbox.prop("checked",!checked);if(checked)$this.removeClass("ui-selected");else $this.addClass("ui-selected");
self.updateTableMenu()}});this.$el.on("click",".tablebuttonbox .actionbutton",{self:this},self.tablebuttonclickhandler);this.$el.find("#tagfilter").each(function(){var $elm=$(this);$elm.tagsinput({tags:function($elm){$.getJSON("api/usertags.json",function(data,status,xhr){self.tags=data.tags;$elm.autocomplete({source:self.tags})})}}).on("change",function(e){var tags=this.value||null;tags=!!tags?"@tag("+tags+")":null;e.stopImmediatePropagation();$elm.trigger("changed",{filters:[{name:"filter_tags",
value:tags},{name:"tags",value:this.value},{name:"start",value:"0"}]})})});this.$el.on("click tab",".tablemenu a",{self:this},self.handleTableMenu).on("change",".selectallasmultiedit",{self:this},self.toggleSelectAll).on("change",".tablemultiselectcheckbox",{self:this},self.selectColumn).on("click",".reloadtablelink:not(.disabled)",$.proxy(self.reloadTableLink,this)).on("click","td.col-properties a",{self:this},self.moreInfo).on("click",".tablebuttonbox .actionbutton",{self:this},self.tablebuttonclickhandler).on("change changed",
"div.sensorlookupnew,.select-reloadtablelink:not(.disabled),#tagfilter",$.proxy(self.reloadTableLink,this)).on("destroyed",function(){_Prtg.Events.unsubscribe("datetimpicker.change",$.proxy(self.datetimepickerChangeHandler,self));_Prtg.Events.unsubscribe("newstats.prtg",$.proxy(self.datetimepickerChangeHandler,self))});if(!!self.data.tabletitle)_Prtg.Events.subscribe("newstats.prtg",$.proxy(self.updateTableTitle,self));_Prtg.Events.subscribe("datetimpicker.change",$.proxy(self.datetimepickerChangeHandler,
self))};prtgTable.prototype.updateTableTitle=function(e){this.params.tabletitle=this.data.tabletitle.printf(_Prtg.lastStats);this.$el.find(".tabletitle th>a").text(this.params.tabletitle)};prtgTable.prototype.tablebuttonclickhandler=function(e){$(this).append($("<div/>",{"class":"ajax-loader-small ajax-loader-small-inline"}))};prtgTable.prototype.moreInfo=function(e){var $self=$(this);$self.parents("td").find("ul.property-list").toggleClass("hidden");$self.toggleClass("folded");$self.hasClass("folded")?
$self.text($self.data("hide")):$self.text($self.data("show"))};prtgTable.prototype.datetimepickerChangeHandler=function(e){var self=this;var update=false;var startpicker=this.$el.find(".table_datepicker_fromtodate input.table_datepicker_dstart.orginal_input");var endpicker=this.$el.find(".table_datepicker_fromtodate input.table_datepicker_dend.orginal_input");if(!startpicker.length&&!endpicker.length)return;startpicker=startpicker.data("plugin_prtgDatetimepicker");endpicker=endpicker.data("plugin_prtgDatetimepicker");
var startdate=startpicker.$el.val();var enddate=endpicker.$el.val();self.$el.find(".pagenavigation ").addClass("ajax-loader-small");if(this.params["filter_drel"]){update=true;delete this.params["filter_drel"]}if(!!startdate){update=true;this.params["filter_dstart"]=startdate}else{update=update||this.params.hasOwnProperty("filter_dstart");delete this.params["filter_dstart"]}if(!!enddate){update=true;this.params["filter_dend"]=enddate}else{update=update||this.params.hasOwnProperty("filter_dend");delete this.params["filter_dend"]}if(update){delete this.params["start"];
startpicker.$picker.datepicker("destroy");endpicker.$picker.datepicker("destroy");this.refresh({data:this},true)}};prtgTable.prototype.reloadTableLink=function(e,filter){var self=this;var data;self.$el.find(".pagenavigation ").addClass("ajax-loader-small");if(e.type==="change")data=$(e.target).find(":selected").data().reload;else if(e.type==="changed")data=filter.filters;else{e.preventDefault();if($(e.target).is(".ui-icon,i"))data=$(e.target).parent("a").data().reload;else data=$(e.target).data().reload}if(!!data)$.each(data,
function(){if(this.value===null&&self.params.hasOwnProperty(this.name))delete self.params[this.name];else self.params[this.name]=this.value});this.refresh({data:this},true)};prtgTable.prototype.refresh=function(e,force){var self=e.data;self.$el.find("#tagfilter").off();if(self.$el.find(".tablemultiselectcheckbox").length)self.$el.find("tbody.selectable-initialized").removeClass("selectable-initialized").selectable("destroy");if(e.force||force||self.$el.find(".tablemultiselectcheckbox:checked").length===
0)$.ajax({url:self.refreshurl,data:self.params}).done(function(data){self.$form=null;self.$el.children().remove();self.$el.html($($.parseHTML(data)).find("form[refreshurl]"));_Prtg.initPlugins(self.el);self.$el.find("#tagfilter").each(function(){var $elm=$(this);$elm.tagsinput({tags:function($elm){$elm.autocomplete({source:self.tags})}}).on("change",function(e){var tags=this.value||null;tags=!!tags?"@tag("+tags+")":null;e.stopImmediatePropagation();_Prtg.Tip.killPopups();$elm.trigger("changed",{filters:[{name:"filter_tags",
value:tags},{name:"tags",value:this.value},{name:"start",value:"0"}]})})});self.$form=self.$el.find("form[refreshurl]");self.$form.attr("callerid",self.$form.attr("id"));!!self.sortable&&self.sortable.refresh();if(self.$el.find(".tablemultiselectcheckbox").length)self.enableSelectable();_Prtg.Events.publish("loaded.events.prtg",self.$el)})};prtgTable.prototype.handleTableMenu=function(e){var $this=$(this),me=this,self=e.data.self,action=$this.data("action")||"",filter=/^ack/.test(action)==true?'[status="5"]':
"",selected=e.data.self.$el.find(".tablemultiselectcheckbox"+filter+":checked").not(".selectallasmultiedit"),ids=[];if(selected.is("[data-status]"))selected.each(function(){ids.push({objid:$(this).val(),status:$(this).attr("data-status")})});else selected.each(function(){ids.push($(this).val())});function refresh(){self.refresh({data:self,force:true})}if(action==="pause")_Prtg.objectTools.pauseWithComment.call(me,ids);else if(action==="pausefor")_Prtg.objectTools.pauseWithComment.call(me,ids,$this.data("pausefor"));
else if(action==="pauseuntil")_Prtg.objectTools.pauseUntil(ids);else if(action==="resume")_Prtg.objectTools.pauseObject(ids.join(","),1);else if(action==="checknow")_Prtg.objectTools.checkObjectNow(ids.join(","));else if(action==="delete")_Prtg.objectTools.deleteObject(ids,true);else if(action==="ack")_Prtg.objectTools.acknowledgeError.call(me,ids);else if(action==="ackfor")_Prtg.objectTools.acknowledgeError.call(me,ids.join(","),$this.data("ackfor"));else if(action==="ackuntil")_Prtg.objectTools.acknowledgeErrorUntil.call(me,
ids.join(","));else if(action==="simulateerror")_Prtg.objectTools.simulateObject(ids.join(","),1);else if(action==="prio")_Prtg.objectTools.setObjectPriority(ids.join(","),$this.data("prio"));else if(action==="addfav")_Prtg.objectTools.faveObject(ids.join(","),1);else if(action==="removefav")_Prtg.objectTools.faveObject(ids.join(","),0);else if(action==="edit"){if(ids.length)_Prtg.objectTools.editSettingsDialog("/multiedit.htm",ids.join(","),{})}else if(action==="move")_Prtg.objectTools.setObjectPosition.call(me,
ids.join(","),$this.data("move"));else if(action==="discover")_Prtg.objectTools.discoverObjectNow.call(me,ids.join(","));else if(action==="maprotation")window.location.replace("/mapshow.htm?ids="+ids.join(","));else if(action==="maintenace")_Prtg.objectTools.setMaintenanceWindow.call(me,ids);else if(action==="ticket-new")_Prtg.objectTools.ticketAdd.call(me,"new");else if(action==="ticket-edit")_Prtg.objectTools.ticketEdit.call(me,ids);else if(action==="ticket-assign")_Prtg.objectTools.ticketAssign.call(me,
ids);else if(action==="ticket-resolve")_Prtg.objectTools.ticketResolve.call(me,ids);else if(action==="ticket-close")_Prtg.objectTools.ticketClose.call(me,ids);else if(action==="ticket-reopen")_Prtg.objectTools.ticketReopen.call(me,ids);else if(action==="ticket-prio")_Prtg.objectTools.ticketPriority.call(me,ids,$this.data("prio"));return false};prtgTable.prototype.toggleSelectAll=function(e){var self=e.data.self;if(!$(this).prop("checked")){self.$el.find(".tablemultiselectcheckbox").prop("checked",
false);self.$el.find(".ui-selected").removeClass("ui-selected")}else self.$el.find(".tablemultiselectcheckbox").prop("checked",true).closest("tr").addClass("ui-selected");self.updateTableMenu()};prtgTable.prototype.enableSelectable=function(){var self=this;this.$el.find("tbody").selectable({start:function(){self.$el.find(".selectallasmultiedit").prop("checked",false)},stop:function(){self.updateTableMenu()},selecting:function(event,ui){$(ui.selecting).find(".tablemultiselectcheckbox").prop("checked",
true)},unselecting:function(event,ui){$(ui.unselecting).find(".tablemultiselectcheckbox").prop("checked",false)},selected:function(event,ui){$(ui.selected).find(".tablemultiselectcheckbox").prop("checked",true)},distance:15,filter:"tr:not(.notselectable)",cancel:"a, input, option, .notselectable, .detailpageoverview>tr, .tablewithstyles, .sorter"}).addClass("selectable-initialized")};prtgTable.prototype.selectColumn=function(e){var $this=$(this);if($this.hasClass("selectallasmultiedit"))return;if($this.is(":checked"))$this.closest("tr").addClass("ui-selected");
else $this.closest("tr").removeClass("ui-selected");e.data.self.updateTableMenu()};prtgTable.prototype.updateTableMenu=function(){var $menu=this.$el.find(".tablemenu .jd_menu");if(this.$el.find(".tablemultiselectcheckbox:checked").length>0){$menu.parent().removeClass("invisible");if($menu.parents("table").width()-$menu.position().left<200)$menu.addClass("flyoutleft");if(this.$el.find('.tablemultiselectcheckbox[status="5"]:checked').length===0)$menu.find("[ack]").hide();else $menu.find("[ack]").show()}else $menu.removeClass("flyoutleft").parent().addClass("invisible")};
_Prtg.Plugins.registerPlugin(pluginName,prtgTable)})(jQuery,window,document);
